version: '3.3'
services:
  ui:
    build: ./ui
    ports:
      - '80:80'
    depends_on:
      - api
  api:
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
    command: bash -c "/usr/wait-for-it.sh --timeout=0 mongo:27017 && npm start"
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    command: --quiet
